### ISSUE TITLE
変数名を改善したほうが良い

### ISSUE THREAD

**Issue by forli1115** [yasuseri/ProjExD#8]
https://github.com/yasuseri/ProjExD/blob/9ce6f1335f1c74807810a4fd36b18414e7b264a7/ex02/calc.py#L15

以降の行でres_sin1を用いるのであれば、この行のres_sinをres_sin1にし、以降の行をres_sin2のようにすると分かりやすくなるのではないかと考えた。

**Comment by yasuseri** [comment]
sinの変数名を変更いたしました。意見ありがとうございます。
